In [59]:
# Import dependencies
import pandas as pd
from lxml import etree
from urllib.request import urlopen
from io import BytesIO
from zipfile import ZipFile

# Overheidsorganisaties
We gebruiken het [Register Internetdomeinen
Overheid](https://organisaties.overheid.nl/domeinen) om een lijst van URLs die
door de Rijksoverheid in gebruik zijn te vinden.

In [26]:
# Load external files
rio_xml_str = urlopen("https://organisaties.overheid.nl/archive/exportRIO.xml").read()

In [55]:
rio_xml_root = etree.fromstring(rio_xml_str)
rio_namespaces = { "p": "https://organisaties.overheid.nl/static/schema/oo/export/0.0.3" }

rio_list = []
for organisatie in rio_xml_root.iter():
    for url in organisatie.findall(".//p:domein", rio_namespaces):
        rio_list.append({ 
            "organisatie": getattr(organisatie.find(".//p:naam", rio_namespaces), "text", None),
            "url": url.find(".//p:url", rio_namespaces).text, 
        })

rio_df = pd.DataFrame(rio_list)
rio_df

               organisatie                                url
0      Algemene Rekenkamer  http://mailfilter01.rekenkamer.nl
1      Algemene Rekenkamer   http://rekenkamer.sitearchief.nl
2      Algemene Rekenkamer       http://webmail.rekenkamer.nl
3      Algemene Rekenkamer  http://www.checkjeschoolgebouw.nl
4      Algemene Rekenkamer  http://www.rekenkamerhuisstijl.nl
...                    ...                                ...
20809                 None                https://www.atkm.nl
20810   Wetterskip Fryslân       https://wetterskipfryslan.nl
20811   Wetterskip Fryslân             https://woudagemaal.nl
20812                 None       https://wetterskipfryslan.nl
20813                 None             https://woudagemaal.nl

[20814 rows x 2 columns]

In [58]:
len(rio_df['organisatie'].unique())

191

# Bedrijven
Voor het opstellen van een lijst van bedrijven gebruiken we de [Open Data Set van
het KVK Handelsregister](https://www.kvk.nl/producten-bestellen/kvk-handelsregister-open-data-set/).

In [63]:
kvk_bytes = urlopen("https://static.kvk.nl/download/kvk-open-data-set-handelsregister.zip").read()

In [65]:
kvk_zip = ZipFile(BytesIO(kvk_bytes))
kvk_csv = kvk_zip.open("kvk-open-data-set-handelsregister.csv")
kvk_df = pd.read_csv(kvk_csv, on_bad_lines="skip",sep=";")
kvk_df

/var/folders/sv/qt_l0qbs34d2llcr4bj5j35r0000gn/T/ipykernel_66840/2479882996.py:3: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  kvk_df = pd.read_csv(kvk_csv, on_bad_lines="skip",sep=";")

,Plaats bezoekadres,Hoofd-/nevenvestiging,Rechtsvormcode,Rechtsvorm,Hoofdactiviteit code,Omschrijving hoofdactiviteit,Nevenactiviteit1,Nevenactiviteit1 omschrijving,Nevenactiviteit2,Nevenactiviteit2 omschrijving,...,Datum oprichting,Datum akte oprichting,Datum organisatie,Datum vestiging,Datum huidig bezoekadres,Datum opheffing,Datum voortzetting,Indicator surseance - faillissement - schuldsanering,Boekjaar,Datum deponering jaarstuk
0,Leeuwarden,H,BV,Besloten Vennootschap,6420.0,Financiële holdings,68204.0,Verhuur van onroerend goed (niet van woonruimte),NaN,NaN,...,19720516.0,19720516.0,19720516.0,19930501.0,20001108.0,NaN,NaN,NaN,2022.0,20240212.0
1,Surhuisterveen,H,BV,Besloten Vennootschap,47741.0,Winkels in drogisterij-artikelen,47742.0,Winkels in medische en orthopedische artikelen,47911.0,Detailhandel via internet in voedingsmiddelen ...,...,20060721.0,20060721.0,20060721.0,20150318.0,20231227.0,NaN,NaN,NaN,2023.0,20240515.0
2,Leeuwarden,H,EMZ,Eenmanszaak,47791.0,Winkels in antiek,47591.0,Winkels in meubels,NaN,NaN,...,19010000.0,NaN,19010000.0,19010000.0,19010000.0,NaN,NaN,NaN,NaN,NaN
3,Sneek,H,VOF,Vennootschap Onder Firma,4726.0,Winkels in tabaksproducten,NaN,NaN,NaN,NaN,...,20010101.0,NaN,20010101.0,19081100.0,19081100.0,NaN,NaN,NaN,NaN,NaN
4,Harlingen,H,BV,Besloten Vennootschap,6420.0,Financiële holdings,NaN,NaN,NaN,NaN,...,19920327.0,19920327.0,19920327.0,19950531.0,20090901.0,NaN,NaN,NaN,2022.0,20240115.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3724231,Doetinchem,H,BV,Besloten Vennootschap,70102.0,Holdings (geen financiële),NaN,NaN,NaN,NaN,...,20240828.0,20240828.0,20240828.0,20240828.0,20240828.0,NaN,NaN,NaN,NaN,NaN
3724232,Arnhem,H,BV,Besloten Vennootschap,5829.0,Overige uitgeverijen van software,NaN,NaN,NaN,NaN,...,20240828.0,20240828.0,20240828.0,20240828.0,20240828.0,NaN,NaN,NaN,NaN,NaN
3724233,Purmerend,H,BV,Besloten Vennootschap,70102.0,Holdings (geen financiële),NaN,NaN,NaN,NaN,...,20240829.0,20240829.0,20240829.0,20240829.0,20240829.0,NaN,NaN,NaN,NaN,NaN
3724234,Heerhugowaard,H,BV,Besloten Vennootschap,68204.0,Verhuur van onroerend goed (niet van woonruimte),NaN,NaN,NaN,NaN,...,20240829.0,20240829.0,20240829.0,20240829.0,20240829.0,NaN,NaN,NaN,NaN,NaN
3724235,Amsterdam,H,BV,Besloten Vennootschap,70102.0,Holdings (geen financiële),NaN,NaN,NaN,NaN,...,20240829.0,20240829.0,20240829.0,20240829.0,20240829.0,NaN,NaN,NaN,NaN,NaN